src/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

src/contact/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('email/', views.emailView, name='email'),
    path('success/', views.successView, name='success'),
]

src/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>Hot-Food</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/lightbox/simpleLightbox.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/jquery-ui/jquery-ui.css' %}" />
  <!-- main css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Permanent+Marker" />
  <style>
  h2 {
    font-family: Permanent Marker;
    font-size: 24px;
    font-style: normal;
    font-variant: normal;
    font-weight: 700;
    line-height: 26.5px; }
  h3 {
    font-family: Permanent Marker;
    font-size: 24px;
    font-style: normal;
    font-variant: normal;
    font-weight: 700;
    line-height: 26.4px; }
  h4 {
    font-family: monospace;
    font-size: 24px;
    font-style: normal;
    font-variant: normal;
    font-weight: 700;
    line-height: 26.4px; }
  </style>

</head>


<body>
  <header class="header_area">
    <div class="main_menu">
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light w-100">
          <!-- Brand and toggle get grouped for better mobile display -->
          <a class="navbar-brand logo_h" href="#">
              <img src="{% static 'img/logo.png' %}" alt="" />
          </a>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse offset w-100" id="navbarSupportedContent">
            <div class="row w-100 mr-0">
              <div class="col-lg-7 pr-0">
                <ul class="nav navbar-nav center_nav pull-right">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'myapp:product_list' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'cart:cart_detail' %}">Cart</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'contact:email' %}">Contact</a>
                    </li>
                </ul>
              </div>
            </div>
          </div>
        </nav>
      </div>
    </div>
  </header>

  {% block content %}

  {% endblock %}

  <footer class="footer-area section_gap">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
  </footer>

  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/stellar.js' %}"></script>
  <script src="{% static 'vendors/lightbox/simpleLightbox.min.js' %}"></script>
  <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
  <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'vendors/isotope/isotope-min.js' %}"></script>
  <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
  <script src="{% static 'js/mail-script.js' %}"></script>
  <script src="{% static 'vendors/jquery-ui/jquery-ui.js' %}"></script>
  <script src="{% static 'vendors/counter-up/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'vendors/counter-up/jquery.counterup.js' %}"></script>
  <script src="{% static 'js/theme.js' %}"></script>
</body>

</html>

src/templates/detail.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="product_image_area"style="margin-bottom: 35%;">
      <div class="container">
        <div class="row s_product_inner">
          <div class="col-lg-6"style="margin-bottom: 15%;">
            <div class="s_product_img" style="padding-top: 15px;">
              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="d-block w-100" src="{{ product.image.url }}" alt="First slide"/>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-5 offset-lg-1">
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
              <div class="s_product_text">
                <h3>{{ product.name }}</h3>
                <h2>$ {{ product.price }}</h2>
                <ul class="list">
                  <li>
                    <a class="active" href="#">
                      <span>Category</span> : ${{ product.category }}</a
                    >
                  </li>
                  <li>
                    <a href="#"> <span>Availibility</span> : In Stock</a>
                  </li>
                </ul>
                    <div class="card_area"style="margin-top: 8%; ">
                        {{ cart_product_form|crispy }}
                        {% csrf_token %}
                        <button class="btn btn-ordinary" style="margin-left: 20px; margin-top: -20px;" input type="submit""><h3>Add to Cart</h3></button>
                    </div>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

src/templates/list.html
{% extends 'base.html' %}
{% block content %}
<section class="offer_area">
    <div class="container"style="height:420px; margin-bottom: 2%; margin-top: -6%;">
      <div class="row justify-content-center">
        <div class="offset-lg-4 col-lg-6 ml-2 text-center">
          <div class="offer_content">
            <h3 class="text-uppercase mb-40 mt-4">all non-veg food</h3>
            <h2 class="text-uppercase">50% off</h2>
            <a href="#" class="genric-btn success-border circle mb-20 mt-5">Discover Now</a>
          </div>
        </div>
      </div>
    </div>
  </section>
      <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12">
          <div class="main_title" style="font-family: Permanent Marker; padding-left: 16px;">
            <h2><span>Featured Hot Food</span></h2>
          </div>
        </div>
      </div>
        <div class="row flex-row-reverse">
          <div class="col-lg-9">
            <div class="latest_product_inner">
              <div class="row">
                {% for product in products %}
                <div class="col-lg-4 col-md-6">
                  <div class="single-product">
                    <div class="product-img">
                      <img class="card-img"src="{{ product.image.url }}"alt=""/>
                    </div>
                    <div class="product-btm">
                      <a href="{{ product.get_absolute_url }}" class="d-block">
                        <h4>{{ product.name }}</h4>
                      </a>
                      <div class="mt-3">
                        <span class="mr-4">$ {{ product.price }}</span>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="left_sidebar_area">
              <aside class="left_widgets p_filter_widgets">
                <div class="l_w_title">
                  <h3>Browse Categories</h3>
                </div>
                <div class="widgets_inner">
                  <ul class="list">
                    <li>
                      <a href="{% url 'myapp:product_list' %}">All Foods</a>
                    </li>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="nav-item"{% endif %}>
                      <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                    {% endfor %}
                  </ul>
                </div>
              </aside>

              <aside class="left_widgets p_filter_widgets" <style="margin-bottom: 20%">
              </style>
                <div class="l_w_title">
                  <h3>Browse By Shops</h3>
                </div>
                <div class="widgets_inner">
                  <ul class="list">
                    <li>
                      <a href="#">Apple</a>
                    </li>
                    <li>
                      <a href="#">Asus</a>
                    </li>
                    <li class="active">
                      <a href="#">Gionee</a>
                    </li>
                    <li>
                      <a href="#">Micromax</a>
                    </li>
                    <li>
                      <a href="#">Samsung</a>
                    </li>
                  </ul>
                </div>
              </aside>
            </div>
          </div>
        </div>
      </div>
{% endblock %}