src/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

src/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

src/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('admin/order/<int:order_id>/pdf/',views.admin_order_pdf,name='admin_order_pdf'),
    path('create/', views.order_create, name='order_create'),
]

src/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)    

src/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from myapp.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

src/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
<div id="all">
                <div id="content">
                  <div class="container" style="margin-top: 4%; margin-bottom: 10%;">
                    <div class="row bar">
                      <div class="col-lg-12" style="color: black; margin-bottom: 4%;">
                        {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                        <h2>You have {{ total_items }} item{{ total_items|pluralize }} in your cart</h2>
                        {% else %}
                        Your cart is empty.
                        {% endif %}
                        {% endwith %}
                      </div>
                      <div id="basket" class="col-lg-9">
                        <div class="box mt-0 pb-0 no-horizontal-padding">
                          <form method="get" action="shop-checkout1.html">
                            <div class="table-responsive">
                              <table class="table" style="font-family: Permanent Marker;">
                                <thead>
                                  <tr>
                                    <th colspan="2">Product</th>
                                    <th>Quantity</th>
                                    <th>price</th>
                                    <th colspan="2">Total</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  {% for item in cart %}
                                  {% with product=item.product %}
                                  <tr>
                                    <td><a href="{{ product.get_absolute_url }}"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="" class="img-fluid"></a></td>
                                    <td>{{ product.name }}</td>
                                    <td>
                                      <form action="{% url 'cart:cart_add' product.id %}" method="post">{{ item.update_quantity_form.quantity }}
                                      {{ item.update_quantity_form.update }}
                                      <input type="submit" value="Update">
                                      {% csrf_token %}
                                      </form>
                                    </td>
                                    <td>${{ item.price }}</td>
                                    <td>${{ item.total_price }}</td>
                                    <td><a href="{% url 'cart:cart_remove' product.id %}"><i class="fa fa-trash-o"></i></a></td>
                                  </tr>
                                  {% endwith %}
                                  {% endfor %}
                                </tbody>
                              </table>
                            </div>
                            <div class="box-footer d-flex justify-content-between align-items-center">
                              <div class="left-col"><a href="{% url 'myapp:product_list' %}" class="btn btn-secondary">Continue shopping</a></div>
                              <div class="right-col"><a href="{% url 'orders:order_create' %}" class="btn btn-secondary"><i class="fa fa-credit-card"></i> Proceed to checkout</a></div>
                            </div>
                          </form>
                        </div>

                      </div>
                      <div class="col-lg-3">
                        <div id="order-summary" class="box mt-0 mb-4 p-0">
                          <div class="box-header mt-0">
                            <h3>Order summary</h3>
                          </div>
                          <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>
                          <div class="table-responsive">
                            <table class="table">
                              <tbody>
                                <tr class="total">
                                  <td>Order Total</td>
                                  <th>${{ cart.get_total_price }}</th>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>


{% endblock %}